# Generated by Django 5.1.6 on 2025-02-12 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "number_seats",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "stock",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="EvenBus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="Give some description to this even.", max_length=512
                    ),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=True, verbose_name="reserved"),
                ),
                (
                    "available_seats",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("departure", models.CharField(max_length=64)),
                ("destination", models.CharField(max_length=64)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="evenements.bus"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvenMaterial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="Give some description to this even.", max_length=512
                    ),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=True, verbose_name="reserved"),
                ),
                (
                    "available_stock",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evenements.material",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvenRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="Give some description to this even.", max_length=512
                    ),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=True, verbose_name="reserved"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evenements.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
