apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yatoute/bookit-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 300Mi  # Augmente légèrement
            limits:
              cpu: 300m
              memory: 500Mi  # Augmente la limite mémoire
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          ports:
            - containerPort: 8000