apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: richard0209/bookit-backend:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config
          ports:
            - containerPort: 8000
              name: gunicorn
          resources:
            requests:
              memory: "2Gi"
              cpu: "1750m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          volumeMounts:
            - name: static-files
              mountPath: /backend/staticfiles  # Dossier des fichiers statiques
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-pvc  # PVC ou type de volume à définir selon ton cas

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ajuste la taille selon tes besoins
