apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookit-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bookit-ensai.kub.sspcloud.fr
        - backend-ensai.kub.sspcloud.fr  # Ajout du backend en HTTPS
      secretName: bookit-tls
  rules:
    - host: bookit-ensai.kub.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: backend-ensai.kub.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
