@startuml diagramme_de_classes

skinparam linetype polyline

class Group {
    +id: int
    +name: str
}

class User {
    +id: int
    +username: str
    +first_name: str
    +last_name: str
    +email: str
    +is_staff : bool
    +is_active : bool
    +date_joined : Date
    +group : Group
}

class Bus {
    +id: int
    +name: str
    +number_seats: int
}

class Room {
    +id: int
    +name: str
}

class Material {
    +id: int
    +name: str
    +stock: int
}

class Event {
    +id: int
    +description: str
    +organizer: User
    +statut: str
}

class EventBus {
    +id: int
    +description: str
    +organizer: User
    +statut: str
    +resource : Bus
    +available_seats : Integer
    +departure : String
    +destination : String
    +departure_time : Date
    +arrival_time : Date
}

class EventRoom {
    +id: int
    +description: str
    +organizer: User
    +statut: str
    +resource : Room
}

class EventMaterial {
    +id: int
    +description: str
    +organizer: User
    +statut: str
    +resource : Material
    +available_stock: int
}

class Reservation {
    +id: int
    +consumer: User
}

class ReservationBus {
    +id: int
    +consumer: User
    +event: EventBus
}

class ReservationRoom {
    +id: int
    +consumer: User
    +event: EventRoom
    +date: Date
    +start_time: time
    +end_time: time
}

class ReservationMaterial {
    +id: int
    +consumer: User
    +event: EventMaterial
    +date: Date
    +start_time: time
    +end_time: time
    +quantity: int
}

'Relations de dépendance
User -right-> Group
EventBus --> Bus
EventRoom --> Room
EventMaterial --> Material
ReservationBus --> EventBus
ReservationRoom -left-> EventRoom
ReservationMaterial --> EventMaterial
Event -up-> User
Reservation --> User

'Héritages évènements
Event <|-- EventBus
Event <|-up- EventRoom
Event <|-- EventMaterial

'Héritages Réservations
Reservation <|-- ReservationMaterial
Reservation <|-- ReservationBus
Reservation <|-- ReservationRoom

'Utilisateur "1" -- "*" Evenement 


@enduml