name: Dockerize

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # Récupèration du code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de QEMU pour la compatibilité multi-architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Configuration de Docker Buildx pour la création d'images multi-architecture
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à DockerHub avec les identifiants stockés dans les secrets GitHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construction de l'image Docker pour le backend et envoi vers DockerHub
      - name: Build and push backend
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: backend
          file: ./backend/Dockerfile
          tags: richard0209/bookit-backend:latest

      # Construction de l'image Docker pour le frontend et envoi vers DockerHub
      - name: Build and push frontend
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: frontend
          file: ./frontend/Dockerfile
          tags: richard0209/bookit-frontend:latest
