name: Dockerize

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: backend
          file: ./backend/Dockerfile
          tags: richard0209/bookit-backend:latest
          
      - name: Build and push frontend
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: frontend
          file: ./frontend/Dockerfile
          tags: richard0209/bookit-frontend:latest
