name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Linting with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=E1101,R0903,W0718 --fail-under 5

    - name: Formatting with isort
      run: |
        python -m isort --profile black backend
        python -m isort --profile black --check backend

    - name: Formatting with black
      run: |
        python -m black backend
        python -m black --check backend  # Vérifier que le code est bien formaté

    - name: Commit changes if any
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git commit -am "Format code with black and isort"
          git push
        else
          echo "No changes to commit"
        fi
