name: Lint

on: 
  push:
    branches:
      - main  # Tu peux spécifier d'autres branches si nécessaire
  pull_request:
    branches:
      - main  # Vérifier les PR vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt 

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files

    - name: Linting with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 5

    - name: Formatting with isort
      run: |
        python -m isort --profile black src/backend
        python -m isort --profile black --check src/backend

    - name: Formatting with black
      run: |
        python -m black src/backend
        python -m black --check src/backend  # Vérifier que le code est bien formaté

    - name: Commit changes if any
      if: ${{ steps.formatting.outputs.changed == 'true' }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git commit -am "Format code with black and isort"
        git push

